### ISSUE TITLE
Panic (and subsequent terraform crash) due to nil pointer dereference

### ISSUE THREAD

**Issue by DethAriel** [splunk-terraform/terraform-provider-signalfx#116]
Hi folks! I've recently run into this issue during `terraform apply` with existing state. The version of terraform I'm running is `0.12.13`, and the `terraform-provider-signalfx` is of version `4.9.2`.

I'd be happy to provide additional information, but was hoping that the trace might be sufficient already :)

```
panic: runtime error: invalid memory address or nil pointer dereference
plugin.terraform-provider-signalfx_v4.9.2_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdf95b3]
plugin.terraform-provider-signalfx_v4.9.2_x4: 
plugin.terraform-provider-signalfx_v4.9.2_x4: goroutine 1065 [running]:
plugin.terraform-provider-signalfx_v4.9.2_x4: github.com/terraform-providers/terraform-provider-signalfx/signalfx.dashboardAPIToTF(0xc00012a0e0, 0xc0001b4500, 0x3, 0xedc6c0)
plugin.terraform-provider-signalfx_v4.9.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/signalfx/resource_signalfx_dashboard.go:877 +0x433
plugin.terraform-provider-signalfx_v4.9.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/signalfx/resource_signalfx_dashboard.go:714 +0x1cd
plugin.terraform-provider-signalfx_v4.9.2_x4: github.com/terraform-providers/terraform-provider-signalfx/signalfx.dashboardRead(0xc00012a0e0, 0xea46c0, 0xc0004d8500, 0xc00012a0e0, 0x0)
plugin.terraform-provider-signalfx_v4.9.2_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000125180, 0xc000517720, 0xea46c0, 0xc0004d8500, 0xc0000a7dc8, 0x0, 0x0)
plugin.terraform-provider-signalfx_v4.9.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x119
plugin.terraform-provider-signalfx_v4.9.2_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000a6a98, 0x12f8840, 0xc0004feed0, 0xc000516b40, 0xc0000a6a98, 0xc0004feed0, 0xc00015bbd0)
plugin.terraform-provider-signalfx_v4.9.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d7
plugin.terraform-provider-signalfx_v4.9.2_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x10605c0, 0xc0000a6a98, 0x12f8840, 0xc0004feed0, 0xc000083b00, 0x0, 0x12f8840, 0xc0004feed0, 0xc000177800, 0x71d)
plugin.terraform-provider-signalfx_v4.9.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x23e
plugin.terraform-provider-signalfx_v4.9.2_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d4000, 0x13034c0, 0xc000001680, 0xc00072d300, 0xc0001321b0, 0x1bfd430, 0x0, 0x0, 0x0)
plugin.terraform-provider-signalfx_v4.9.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:995 +0x466
plugin.terraform-provider-signalfx_v4.9.2_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000d4000, 0x13034c0, 0xc000001680, 0xc00072d300, 0x0)
plugin.terraform-provider-signalfx_v4.9.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:1275 +0xda6
plugin.terraform-provider-signalfx_v4.9.2_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00009a3e0, 0xc0000d4000, 0x13034c0, 0xc000001680, 0xc00072d300)
plugin.terraform-provider-signalfx_v4.9.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:710 +0x9f
plugin.terraform-provider-signalfx_v4.9.2_x4: created by github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
plugin.terraform-provider-signalfx_v4.9.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:708 +0xa1
plugin: plugin process exited: path=/etc/terraform/plugins/terraform-provider-signalfx_v4.9.2_x4 pid=2778 error="exit status 2"
```

**Comment by DethAriel** [comment]
Hey folks! Is anyone looking into this by any chance? Is there any additional information that I could provide that will facilitate the triaging process?

**Comment by cory-signalfx** [comment]
Hey Ruslan!

Sorry for the delay, I somehow missed this in the rush of conferences lately. I’ll get to this tomorrow for sure!

--- Cory Watson Technical Evangelist Splunk

**Comment by cory-signalfx** [comment]
Hey @DethAriel! I've asked Hashi for a build of the provider that includes the fix in #120. Thanks for flagging this and sorry you hit it!

**Comment by DethAriel** [comment]
Thank you so much for such a quick fix! I see that this is now in `4.10.2 (Unreleased)`, is there any ETA on when is this going to be released?

**Comment by cory-signalfx** [comment]
I've asked Hashi and they are working on it now. Should be in a few hours at the latest.

**Comment by cory-signalfx** [comment]
The build finished, so it should be available soon if not already available!

**Comment by DethAriel** [comment]
worked like a charm, thanks a lot @cory-signalfx!
