### ISSUE TITLE
Can not create SignalFx Detector Resource

### ISSUE THREAD

**Issue by bhelemilan** [splunk-terraform/terraform-provider-signalfx#146]
Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
2020-02-06T13:06:28.692-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1a13195]
2020-02-06T13:06:28.692-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 
2020-02-06T13:06:28.692-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: goroutine 27 [running]:
2020-02-06T13:06:28.692-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: github.com/terraform-providers/terraform-provider-signalfx/signalfx.detectorAPIToTF(0xc00032c690, 0xc000b2a000, 0xb, 0x1adf100)
2020-02-06T13:06:28.692-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:490 +0xc75
2020-02-06T13:06:28.692-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: github.com/terraform-providers/terraform-provider-signalfx/signalfx.detectorCreate(0xc00032c690, 0x1aa8f80, 0xc0000cec00, 0x2, 0x2836f00)
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:427 +0x3a3
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0002fc880, 0xc0003e6370, 0xc000216b80, 0x1aa8f80, 0xc0000cec00, 0xc000512101, 0xc00009c190, 0x1b309c0)
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:286 +0x3b4
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0002fdb80, 0xc000215a58, 0xc0003e6370, 0xc000216b80, 0xc00025c2c8, 0xc0002b8080, 0x1b32940)
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0002b84b0, 0x1f02d40, 0xc00024d950, 0xc0000e4180, 0xc0002b84b0, 0xfa, 0xc000408bd0)
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:889 +0x9ac
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1c60100, 0xc0002b84b0, 0x1f02d40, 0xc00024d950, 0xc0001266e0, 0x0, 0x1f02d40, 0xc00024d950, 0xc000287800, 0xabc)
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3217 +0x23e
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000157200, 0x1f0e2a0, 0xc000157500, 0xc0004f4e00, 0xc0003b6b40, 0x280bbc0, 0x0, 0x0, 0x0)
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:966 +0x470
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000157200, 0x1f0e2a0, 0xc000157500, 0xc0004f4e00, 0x0)
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:1245 +0xd25
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000476490, 0xc000157200, 0x1f0e2a0, 0xc000157500, 0xc0004f4e00)
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:685 +0x9f
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: created by github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2020-02-06T13:06:28.693-0500 [DEBUG] plugin.terraform-provider-signalfx_v4.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:683 +0xa1

**Comment by bhelemilan** [comment]
Looks like some of the detectors were created even when terraform reported crash. I see the detectors created in SignalFx Detectors Dashboard.

**Comment by cory-signalfx** [comment]
Hey @bhelemilan, sorry I missed this. Thanks for the dump.

From this looks of this trace, that bug was fixed in [version 4.8.1](https://github.com/terraform-providers/terraform-provider-signalfx/blob/master/CHANGELOG.md#481-september-23-2019) and you look to be using 4.0.0. If you upgrade to the latest, this should get cleared up!

**Comment by bhelemilan** [comment]
Thanks, able to create with new version.
