### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by iNikem** [splunk-terraform/terraform-provider-signalfx#370]
I got the following crash when using SignalFx terraform provider:

```
╷
│ Error: Request cancelled
│ 
│   with signalfx_detector.waitlisted_trial,
│   on waitlisted_trial.tf line 1, in resource "signalfx_detector" "waitlisted_trial":
│    1: resource "signalfx_detector" "waitlisted_trial" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-signalfx_v6.12.0 plugin:

panic: interface conversion: interface {} is int, not int64

goroutine 1429 [running]:
github.com/splunk-terraform/terraform-provider-signalfx/signalfx.getVisualizationOptionsDetector(0x19b22ec?)
	github.com/splunk-terraform/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:419 +0x35d
github.com/splunk-terraform/terraform-provider-signalfx/signalfx.getPayloadDetector(0x0?)
	github.com/splunk-terraform/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:383 +0xac5
github.com/splunk-terraform/terraform-provider-signalfx/signalfx.detectorUpdate(0xc0005d2cb0, {0x1830400?, 0xc000104b00})
	github.com/splunk-terraform/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:655 +0x4a
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0005e8b40, 0xc0002ead20, 0xc0001cdfc0, {0x1830400, 0xc000104b00})
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:316 +0x3e3
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000046080, 0xc0007bb960, 0xc000646fe0?, 0x1f?)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e060, {0xc0005d2000?, 0x10b1826?}, 0xc0005d2000)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1955580?, 0xc00000e060}, {0x1b1cd08, 0xc00084b380}, 0xc0009ea180, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004be480, {0x1b1f9c0, 0xc000010000}, 0xc00024ea00, 0xc0002822d0, 0x20187a0, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc0004be480, {0x1b1f9c0, 0xc000010000}, 0xc00024ea00, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1313 +0xa05
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.27.1/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.27.1/server.go:720 +0xea

Error: The terraform-provider-signalfx_v6.12.0 plugin crashed!
```

**Comment by atoulme** [comment]
Closing as inactive. Please open an internal support request if this is still occuring.
