### ISSUE TITLE
Terraform Crash on adding `show_data_markers` to SignalFx Detector

### ISSUE THREAD

**Issue by ejwmoreau** [splunk-terraform/terraform-provider-signalfx#90]
Terraform Version: 0.12.7
SignalFx Provider Version: 4.6.3

Note: I've substituted most of the content that I think is irrelevant. Let me know if you'd like more content from the detector :) 

When we try to add the `show_data_markers = true` option to an existing detector, we get this Terraform crash. It seems like `show_data_markers = true` does get applied to the detector, but this crash is still concerning

Let me know if there's anything else you'd like me to provide in investigating this problem!

Crash output:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # signalfx_detector.detector_one[0] will be updated in-place
  ~ resource "signalfx_detector" "detector_one" {
        id                = "EFH5e75A0AA"
        name              = "<name>"
        program_text      = "<program_text>"
      + show_data_markers = true
        teams             = [
            "EEPoVSuA0AA",
        ]
        url               = "https://atlassian.signalfx.com/#/detector/EFH5e75A0AA"

        rule {
            description           = "<desc>"
            detect_label          = "<detect_label>"
            disabled              = false
            notifications         = [
                "Team,EEPoVSuA0AA",
            ]
            parameterized_body    = "<body>"
            parameterized_subject = "<subject>"
            severity              = "Minor"
            tip                   = "<tip>"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

signalfx_detector.detector_one[0]: Modifying... [id=EFH5e75A0AA]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xe3dafe]
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: goroutine 25 [running]:
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: github.com/terraform-providers/terraform-provider-signalfx/signalfx.detectorAPIToTF(0xc000169810, 0xc0000321e0, 0xb, 0xf10160)
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:416 +0xbce
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: github.com/terraform-providers/terraform-provider-signalfx/signalfx.detectorUpdate(0xc000169810, 0xed8640, 0xc000370480, 0x24, 0x1c92580)
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/signalfx/resource_signalfx_detector.go:483 +0x44b
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000149280, 0xc0005c2d70, 0xc0005bef80, 0xed8640, 0xc000370480, 0xc00023b701, 0x1c66710, 0xf62860)
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:293 +0x264
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000472180, 0xc000189a58, 0xc0005c2d70, 0xc0005bef80, 0xc00023ef28, 0xc00000e5e0, 0xf648a0)
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000142538, 0x1346ce0, 0xc0002b8ae0, 0xc0003762a0, 0xc000142538, 0xc0002b8ae0, 0xc0001f0bd0)
2019-09-23T05:42:47.845Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:885 +0x894
2019-09-23T05:42:47.846Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1095600, 0xc000142538, 0x1346ce0, 0xc0002b8ae0, 0xc0005c2af0, 0x0, 0x1346ce0, 0xc0002b8ae0, 0xc0001c5000, 0x17bd)
2019-09-23T05:42:47.846Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3217 +0x23e
2019-09-23T05:42:47.846Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000552900, 0x1351c60, 0xc000553080, 0xc00014e500, 0xc00035cd80, 0x1c66b80, 0x0, 0x0, 0x0)
2019-09-23T05:42:47.846Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:966 +0x470
2019-09-23T05:42:47.846Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000552900, 0x1351c60, 0xc000553080, 0xc00014e500, 0x0)
2019-09-23T05:42:47.846Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:1245 +0xd25
2019-09-23T05:42:47.846Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000146160, 0xc000552900, 0x1351c60, 0xc000553080, 0xc00014e500)
2019-09-23T05:42:47.846Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:685 +0x9f
2019-09-23T05:42:47.846Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: created by github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-09-23T05:42:47.846Z [DEBUG] plugin.terraform-provider-signalfx_v4.6.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-signalfx/vendor/google.golang.org/grpc/server.go:683 +0xa1
2019-09-23T05:42:47.850Z [DEBUG] plugin: plugin process exited: path=/etc/terraform/plugins/terraform-provider-signalfx_v4.6.3_x4 pid=85 error="exit status 2"
2019/09/23 05:42:47 [DEBUG] signalfx_detector.detector_one[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2019/09/23 05:42:47 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/09/23 05:42:47 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/09/23 05:42:47 [TRACE] EvalWriteState: writing current state object for signalfx_detector.detector_one[0]
2019/09/23 05:42:47 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2019/09/23 05:42:47 [TRACE] EvalApplyProvisioners: signalfx_detector.detector_one[0] is not freshly-created, so no provisioning is required
2019/09/23 05:42:47 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/09/23 05:42:47 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/09/23 05:42:47 [TRACE] EvalWriteState: writing current state object for signalfx_detector.detector_one[0]
2019/09/23 05:42:47 [TRACE] <root>: eval: *terraform.EvalIf
2019/09/23 05:42:47 [TRACE] <root>: eval: *terraform.EvalIf
2019/09/23 05:42:47 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2019/09/23 05:42:47 [TRACE] <root>: eval: *terraform.EvalApplyPost
2019/09/23 05:42:47 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2019/09/23 05:42:47 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/09/23 05:42:47 [TRACE] [walkApply] Exiting eval tree: signalfx_detector.detector_one[0]
2019/09/23 05:42:47 [TRACE] vertex "signalfx_detector.detector_one[0]": visit complete
2019/09/23 05:42:47 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2019/09/23 05:42:47 [TRACE] dag/walk: upstream of "provider.signalfx (close)" errored, so skipping
2019/09/23 05:42:47 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019/09/23 05:42:47 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2019/09/23 05:42:47 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2019/09/23 05:42:47 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2019/09/23 05:42:47 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2019/09/23 05:42:47 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2019-09-23T05:42:47.863Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by joshuaspence** [comment]
I think it was caused by https://github.com/signalfx/signalfx-go/commit/311c2130f01ed5ab45ca4e1670a9a95a172a0994, in which case the fix might be to add an additional guard condition [here](https://github.com/terraform-providers/terraform-provider-signalfx/blob/v4.7.0/signalfx/resource_signalfx_detector.go#L416).

**Comment by cory-signalfx** [comment]
Any chance you can snag the `crash.log` it spit out?

I don't see anything obvious to protect against for guard conditions, @joshuaspence. Which property are you suggesting?

Also there's been at least one crashing fix since 4.6.3. so upgrading may help you as well. Locally just changing the `show_data_markers` isn't causing this for me. If it applied the change but crashed, it's likely it's something on the read of the response. (Which fits @joshuaspence's idea!)

**Comment by cory-signalfx** [comment]
Oh, i see it @joshuaspence. You're referring to the `Time`. Lemme try and repro that!

**Comment by ejwmoreau** [comment]
Thanks! :D I'll include the crash.log file next time I report another crash :)
